name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality_and_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # fallbacks if you don't have a dev reqs file
          pip install -q --disable-pip-version-check pytest pytest-cov ruff mypy bandit pip-audit build

      - name: Lint (ruff)
        run: ruff check .

      - name: Type-check (mypy)
        run: mypy .

      - name: Security scan (bandit)
        run: bandit -r .

      - name: Dependency audit (pip-audit)
        # non-blocking; change to just `pip-audit -r requirements.txt` to fail the build on vulnerable deps
        run: |
          if [ -f requirements.txt ]; then pip-audit -r requirements.txt || true; else echo "no requirements.txt"; fi

      - name: Run tests (with coverage)
        run: |
          pytest -q --cov=. --cov-report=xml --cov-report=term-missing --cov-fail-under=80

      - name: Upload coverage.xml (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml

  build_package:
    needs: quality_and_tests
    runs-on: ubuntu-latest
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build wheel/sdist
        run: |
          python -m pip install -U pip
          pip install build
          python -m build
      - name: Upload dist/ (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
