name: scheduled monitoring

on:
  schedule:
    # every 15 minutes (CRON is UTC!)
    - cron: "*/15 * * * *"
  workflow_dispatch: {}

jobs:
  run:
    runs-on: [self-hosted, Windows]   # <<< use YOUR self-hosted Windows runner
    defaults:
      run:
        shell: 'powershell -NoProfile -ExecutionPolicy Bypass -File {0}'
    env:
      MONITOR_LOG: C:\monitoring\app\server_monitoring.log

    steps:
      - name: Run monitoring (one email only)
        run: |
          Set-Location C:\monitoring\app
          & .\.venv\Scripts\python.exe .\monitoring1.py all --one-email -p C:\

      - name: Show last 40 lines of log (for debugging)
        if: always()
        run: |
          Write-Host "MONITOR_LOG: $env:MONITOR_LOG"
          if (Test-Path $env:MONITOR_LOG) {
            Get-Content $env:MONITOR_LOG -Tail 40
          } else {
            Write-Host "Log not found."
          }
